// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CreateVehicleController from "./create_vehicle_controller"
application.register("create-vehicle", CreateVehicleController)

import DiscountsIndexController from "./discounts_index_controller"
application.register("discounts-index", DiscountsIndexController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import PositionController from "./position_controller"
application.register("position", PositionController)

import StationsOrderController from "./stations_order_controller"
application.register("stations-order", StationsOrderController)
